# Generated by Django 5.0.4 on 2024-11-28 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters', models.TextField(blank=True, null=True, verbose_name='Characters')),
                ('favorite_character', models.CharField(blank=True, max_length=255, null=True, verbose_name='Favorite Character')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pages')),
                ('favorite_moment', models.TextField(blank=True, null=True, verbose_name='Favorite Moment')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('recommended_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Recommended By')),
                ('quotes', models.TextField(blank=True, null=True, verbose_name='Quotes')),
                ('will_recommend_to_friend', models.BooleanField(default=False, verbose_name='Will Recommend to a Friend')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('book', models.OneToOneField(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='my_book', to='books.mybook', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_journal', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Reading Journal',
                'verbose_name_plural': 'Reading Journals',
                'ordering': ['-created_at'],
            },
        ),
    ]
