# Generated by Django 5.0.4 on 2024-12-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksList', '0003_bookslist_have_journal'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingjournal',
            name='book',
        ),
        migrations.RemoveField(
            model_name='readingjournal',
            name='user',
        ),
        migrations.AddField(
            model_name='readingjournal',
            name='books_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reading_journal', to='booksList.bookslist', verbose_name='Books List Entry'),
            preserve_default=False,
        ),
    ]
