# Generated by Django 5.0.4 on 2024-11-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybook',
            name='is_favourite',
        ),
        migrations.RemoveField(
            model_name='mybook',
            name='read_status',
        ),
        migrations.RemoveField(
            model_name='mybook',
            name='wish_list',
        ),
    ]
