# Generated by Django 5.0.4 on 2024-11-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_mybook_is_favourite_remove_mybook_read_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybook',
            name='profile',
        ),
    ]
