# Generated by Django 5.0.4 on 2024-12-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_mybook_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybook',
            name='have_journal',
            field=models.BooleanField(default=False),
        ),
    ]
