# Generated by Django 5.0.4 on 2024-12-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_mybook_have_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybook',
            name='have_journal',
        ),
    ]
