# Generated by Django 5.0.4 on 2024-12-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_comment_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_time_of_publication'], 'permissions': [('can_approve_comments', 'Can approve comments')]},
        ),
    ]
