# Generated by Django 5.0.4 on 2024-11-28 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0002_remove_mybook_is_favourite_remove_mybook_read_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_status', models.CharField(choices=[('wish_list', 'Wish List'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='wish_list', max_length=15)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.mybook')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'unique_together': {('profile', 'book')},
            },
        ),
    ]
