# Generated by Django 5.0.4 on 2024-12-01 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_mybook_profile'),
        ('booksList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslist',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_list_book', to='books.mybook'),
        ),
    ]
